import {Button} from "@/components/ui/button.tsx";
import {AlertTriangle, Heart, PillIcon, Stethoscope, WandSparkles} from "lucide-react";
import {
    Dialog,
    DialogClose,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
    DialogTrigger
} from "@/components/ui/dialog.tsx";

function PatientHistory() {
    return (
        <div className="w-full">
            <div className="flex justify-end">
                <Dialog>
                    <DialogTrigger asChild>
                        <Button>
                            <WandSparkles className="mr-2"/>
                            <p>AI Summary</p>
                        </Button>
                    </DialogTrigger>
                    <DialogContent className="sm:max-w-3xl">
                        <DialogHeader>
                            <DialogTitle className="text-lg font-semibold">Patient History</DialogTitle>
                            <DialogDescription className="text-xs">
                                Automatically generated by AI.
                            </DialogDescription>
                        </DialogHeader>
                        <div className="grid grid-cols-2 gap-6 mt-2">
                            {/* Left Column */}
                            <div className="space-y-6">
                                {/* Medical history */}
                                <div className="p-4 rounded-lg bg-blue-50/50">
                                    <div className="flex items-center space-x-2 mb-4">
                                        <div className="relative h-7 w-7">
                                            <div className="bg-blue-100 rounded-full h-full w-full absolute"/>
                                            <PillIcon
                                                className="h-4 w-4 absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-blue-600"/>
                                        </div>
                                        <h5 className="text-sm font-semibold text-blue-900">Medical History</h5>
                                    </div>
                                    <div className="flex flex-col space-y-3">
                                        <div>
                                            <p className="text-sm font-medium">Levothyroxine 50mcg daily</p>
                                            <p className="text-shade-500 text-xs">28.02.2024 • Dr. Weber •
                                                Internistische Praxis</p>
                                        </div>
                                        <div>
                                            <p className="text-sm font-medium">Vitamin D3 2000IU daily</p>
                                            <p className="text-shade-500 text-xs">05.12.2023 • Dr. Stubbe •
                                                Hausarztpraxis</p>
                                        </div>
                                        <div>
                                            <p className="text-sm font-medium">Sumatriptan 50mg as needed</p>
                                            <p className="text-shade-500 text-xs">01.03.2024 • Dr. Schmidt • MVZ München
                                                Zentrum</p>
                                        </div>
                                    </div>
                                </div>

                                {/* Current Diagnoses */}
                                <div className="p-4 rounded-lg bg-purple-50/50">
                                    <div className="flex items-center space-x-2 mb-4">
                                        <div className="relative h-7 w-7">
                                            <div className="bg-purple-100 rounded-full h-full w-full absolute"/>
                                            <Stethoscope
                                                className="h-4 w-4 absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-purple-600"/>
                                        </div>
                                        <h5 className="text-sm font-semibold text-purple-900">Current Diagnoses</h5>
                                    </div>
                                    <div className="flex flex-col space-y-3">
                                        <div>
                                            <p className="text-sm font-medium">Diabetes Type 2</p>
                                            <p className="text-shade-500 text-xs">28.02.2024 • Dr. Weber •
                                                Endokrinologie Zentrum</p>
                                        </div>
                                        <div>
                                            <p className="text-sm font-medium">Hypertension</p>
                                            <p className="text-shade-500 text-xs">01.03.2024 • Dr. Schmidt •
                                                Hausarztpraxis</p>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {/* Right Column */}
                            <div className="space-y-6">
                                {/* Allergies & Warnings */}
                                <div className="p-4 rounded-lg bg-red-50/50">
                                    <div className="flex items-center space-x-2 mb-4">
                                        <div className="relative h-7 w-7">
                                            <div className="bg-red-100 rounded-full h-full w-full absolute"/>
                                            <AlertTriangle
                                                className="h-4 w-4 absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-red-600"/>
                                        </div>
                                        <h5 className="text-sm font-semibold text-red-900">Allergies & Warnings</h5>
                                    </div>
                                    <div className="flex flex-col space-y-3">
                                        <div>
                                            <p className="text-sm font-medium">Penicillin - Severe rash</p>
                                            <p className="text-shade-500 text-xs">10.06.2020 • Dr. Müller • Notaufnahme
                                                München Klinik</p>
                                        </div>
                                        <div>
                                            <p className="text-sm font-medium">Latex - Mild reaction</p>
                                            <p className="text-shade-500 text-xs">15.03.2021 • Dr. Schmidt •
                                                Hautarztpraxis</p>
                                        </div>
                                    </div>
                                </div>

                                {/* Recent Vitals */}
                                <div className="p-4 rounded-lg bg-green-50/50">
                                    <div className="flex items-center space-x-2 mb-4">
                                        <div className="relative h-7 w-7">
                                            <div className="bg-green-100 rounded-full h-full w-full absolute"/>
                                            <Heart
                                                className="h-4 w-4 absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-green-600"/>
                                        </div>
                                        <h5 className="text-sm font-semibold text-green-900">Recent Vitals</h5>
                                    </div>
                                    <div className="flex flex-col space-y-3">
                                        <div>
                                            <p className="text-sm font-medium">BP: 128/82</p>
                                            <p className="text-shade-500 text-xs">15.03.2024 • Dr. Stubbe •
                                                Hausarztpraxis</p>
                                        </div>
                                        <div>
                                            <p className="text-sm font-medium">HR: 72 bpm</p>
                                            <p className="text-shade-500 text-xs">15.03.2024 • Dr. Stubbe •
                                                Hausarztpraxis</p>
                                        </div>
                                        <div>
                                            <p className="text-sm font-medium">Weight: 65 kg</p>
                                            <p className="text-shade-500 text-xs">15.03.2024 • Dr. Stubbe •
                                                Hausarztpraxis</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <DialogFooter className="sm:justify-start mt-2">
                            <DialogClose asChild>
                                <Button type="button" variant="secondary" className="text-xs">
                                    Close
                                </Button>
                            </DialogClose>
                        </DialogFooter>
                    </DialogContent>
                </Dialog>
            </div>
            <p>Patient history list here</p>
        </div>
    );
}

export default PatientHistory;